- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/eventprocessor/EventProcessorFactory.java
> [MIST-1008] Set AffinityEventProcessorFactory as a default event processor factory

- mist-core/src/main/java/edu/snu/mist/core/driver/MistMasterConfigs.java
- mist-core/src/main/java/edu/snu/mist/core/master/TaskLoadUpdater.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/AbstractQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/ApplicationAwareQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/PowerOfTwoQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/QueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/RoundRobinQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/package-info.java
- mist-core/src/main/java/edu/snu/mist/core/parameters/QueryAllocationOption.java
- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultClientToMasterMessageImpl.java
- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultDriverToMasterMessageImpl.java
- mist-core/src/test/java/edu/snu/mist/core/master/QueryAllocationManagerTest.java
This PR resolves #1035 via
* Implement round-robin and power-of-two query allocation algorithms.
* Add command line option for selecting query allocation algorithms.
Closes #1035.
> [MIST-1035] Implement group-unaware query allocation algorithms for testing

- mist-core/src/main/java/edu/snu/mist/core/driver/MistDriver.java
- mist-core/src/main/java/edu/snu/mist/core/master/TaskLoadUpdater.java
- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultDriverToMasterMessageImpl.java
This PR resolves #1037 via
* Add missing master-to-task setup connection.
* Fix bugs in retrieving `taskInfo` in `MistMaster`
> [MIST-1037] Fix the problem of task load update

- mist-client/src/main/java/edu/snu/mist/client/MISTQueryControl.java
- mist-common/src/main/avro/driver_to_master_msg.avpr
- mist-core/src/main/java/edu/snu/mist/core/driver/MistDriver.java
- mist-core/src/main/java/edu/snu/mist/core/master/ProxyToTaskMap.java
- mist-core/src/main/java/edu/snu/mist/core/master/TaskLoadUpdater.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/AbstractQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/ApplicationAwareQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/PowerOfTwoQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/QueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/RoundRobinQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/parameters/MasterHostname.java
- mist-core/src/main/java/edu/snu/mist/core/parameters/TaskHostname.java
- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultDriverToMasterMessageImpl.java
- mist-core/src/main/java/edu/snu/mist/core/shared/MQTTSharedResource.java
- mist-core/src/main/java/edu/snu/mist/core/task/MistTask.java
- mist-core/src/test/java/edu/snu/mist/core/master/QueryAllocationManagerTest.java
This PR resolves #1052 via
* Use String hostname for identifying MistTask instead of IPAddress
> [MIST-1052] Use String hostname for identifying MistTask

- mist-core/src/main/java/edu/snu/mist/core/driver/MistMasterConfigs.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/MinLoadQueryAllocationManager.java
This PR resolves #1058 by 
* implementing `MinLoadQueryAllocationManager` that allocates queries to the task that has the minimum load.
> [MIST-1058] Implement minimum load query allocator

- mist-core/src/main/java/edu/snu/mist/core/master/TaskStatsMap.java
- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultDriverToMasterMessageImpl.java
This PR closes #1060 via
* Use the correct `NamedParameter` on `MasterToTaskMessage` port number
* Add logging on task load update
> [MIST-1060] Fix bug on setting up Master-To-Task Proxy

- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultMasterToTaskMessageImpl.java
This PR resolves #1062 via
* Setting missing `groupId` when sending `GroupStats`.
> [MIST-1062] Fix the problem of not updating task loads

- mist-client/src/main/java/edu/snu/mist/client/MISTDefaultExecutionEnvironmentImpl.java
- mist-client/src/main/java/edu/snu/mist/client/MISTExecutionEnvironment.java
- mist-client/src/test/java/edu/snu/mist/client/utils/MockMasterServer.java
- mist-common/src/main/avro/client_to_master_msg.avpr
- mist-core/src/main/java/edu/snu/mist/core/master/MasterSetupFinished.java
- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultClientToMasterMessageImpl.java
- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultDriverToMasterMessageImpl.java
This PR resolves #1051 
* by creating `isReady` method in Mist client and waiting until MistMaster is ready to receive query submission
> [MIST-1051] Fix returning null Task

- mist-core/src/main/java/edu/snu/mist/core/sources/EventGeneratorImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/DefaultCheckpointManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAwareQueryManagerImpl.java
This PR resolves #1074.
The logging message appears only when the `GroupAwareQueryManager` is initialized.
Closes #1074.
> [MIST-1074] Remove checkpointing turned off log message

- mist-core/src/main/java/edu/snu/mist/core/master/allocation/ApplicationAwareQueryAllocationManager.java
This issue resolves #1099 via
* Prevent calling `Random.nextInt()` with argument 0.
> [MIST-1099] Fix IllegalArgument Exception in AAQAM

- mist-core/src/main/java/edu/snu/mist/core/task/QueryManager.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/ApplicationInfo.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultApplicationInfoImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAwareQueryManagerImpl.java
- mist-core/src/test/java/edu/snu/mist/core/task/checkpointing/GroupRecoveryTest.java
This PR resolves #1104 by : 
- creating a `createGroup()` method in `QueryManager` interface
- also binds necessary instances (that belong to `ApplicationInfo` level) to the group (`ExecutionDags`, `QueryIdConfigDagMap`, `ConfigExecutionVertexMap`)
Closes #1104
> [MIST-1104] Decouple initial Group creation from Application creation

- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/DefaultCheckpointManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/ApplicationInfo.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultApplicationInfoImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAllocationTableModifierImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/merging/MergeAwareQueryRemover.java
This PR resolves #1103 by
- adding a `removeGroup()` method to the `ApplicationInfo` interface, which does the opposite of the `addGroup()` method
- removing the `Group` from the `ApplicationInfo` in the `GROUP_REMOVE` case in `GroupAllocationTableModifierImpl`
Closes #1103
>  [MIST-1103] CheckpointManager DeleteGroup deletes all groups

- mist-core/src/main/java/edu/snu/mist/core/operators/OneStreamStateHandlerOperator.java
- mist-core/src/main/java/edu/snu/mist/core/operators/StateHandler.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
This PR resolves #1112.
It puts an empty state if `getMaxAvailableTimestamp` returns null.
Closes #1112
> [MIST-1112] Fix possible null exception in Group Checkpointing

- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAllocationTableModifierImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/eventprocessor/AffinityEventProcessor.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/eventprocessor/AffinityEventProcessorFactory.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/eventprocessor/AffinityRunnable.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/parameters/ProcessingTimeout.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/DefaultGroupRebalancerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/DefaultGroupSplitterImpl.java
This PR resolves #1126 by 
* merging groups in the rebalancing process 
* moving at most half of groups in a group while splitting groups 
* fixing several issues (event processor timeout)
> [MIST-1126] Improve group splitting and merging

- pom.xml
This PR resolves #1132 via
* Add build-helper-maven-plugin for adding generated sources.
> [MIST-1132] Add plugin for adding generated sources

- mist-core/pom.xml
- mist-core/src/main/java/edu/snu/mist/core/replay/EventReplayResult.java
- mist-core/src/main/java/edu/snu/mist/core/replay/EventReplayUtils.java
- mist-core/src/main/java/edu/snu/mist/core/replay/package-info.java
- mist-core/src/test/java/edu/snu/mist/core/replay/EventReplayUtilsTest.java
- mist-core/src/test/java/edu/snu/mist/core/replay/MockReplayServer.java
- mist-core/src/test/java/edu/snu/mist/core/replay/package-info.java
This PR addresses #1135 by:
- adding json-simple to the MIST core's pom.xml, for parsing to and from JSON objects
- adding a EventReplayUtils class with the API (replay, checkpoint, subscribe)
- MockReplayServer, which can be used as a fully functioning replay server
- EventReplayUtilsTest, that is used for testing the EventReplayUtils class
Closes #1135
> [MIST-1135] Implement HTTP API for using a backup server

- mist-core/src/test/java/edu/snu/mist/core/sinks/NettyTextSinkTest.java
This PR resolves #1142 via
* Increasing the time limit for `testNettyTextSink()`.
> [MIST-1142] Increase the time limit for testNettyTextSink

- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultClientToMasterMessageImpl.java
This PR resolves #1155 
* by adding try-catch clauses in `DefaultClientToMasterMessageImpl`
> [MIST-1155] Try-catch exceptions in ClientToMaster

- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/CheckpointManager.java
- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/DefaultCheckpointManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAllocationTableModifierImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAwareQueryManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/DefaultGroupCheckpointStore.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/GroupCheckpointStore.java
This PR solves #1033 via
* Store submitted query lists for each group.
* Read query list file instead of checkpoint file when recovering queries.
> [MIST-1033] Recovery queries with no checkpoints

- mist-core/src/main/java/edu/snu/mist/core/master/recovery/RecoveryStarter.java
This PR closes #1162 via
* Catch `AvroRemoteException` and `InterruptedException` in `RecoveryStarter`.
> [MIST-1162] Fix uncaught exception on RecoveryStarter

- mist-core/src/main/java/edu/snu/mist/core/task/StateSerializer.java
- mist-core/src/main/java/edu/snu/mist/core/task/merging/DefaultExecutionVertexGeneratorImpl.java
This PR closes #1161 via
* Adding external class loaders for deserialization.
* Use internal `SerializeUtils` when (de)serializing the states.
> [MIST-1161] Fix ClassNotFoundException on state deserialization

- mist-core/src/main/java/edu/snu/mist/core/master/recovery/DistributedRecoveryScheduler.java
- mist-core/src/main/java/edu/snu/mist/core/master/recovery/SingleNodeRecoveryScheduler.java
This PR closes #1166 via
* Set conditional variable when there is no failed groups in `RecoveryScheduler`.
> [MIST-1166] Handling recovery with no failed groups

- mist-core/src/main/java/edu/snu/mist/core/task/DefaultConfigDagGeneratorImpl.java
This PR fixes #1174 via
* Check whether `vertexStateWithTimestamp` is null or not in `DefaultConfigDagGeneratorImpl`.
Closes #1174.
> [MIST-1174] Fix NullPointerException on DefaultConfigDagGeneratorImpl
