- LICENSE
> [MIST-988] Add license information to the project root

- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/UtilizationLoadUpdater.java
> [MIST-1000] Fix bug in load updater

- README.md
This PR resolves #996 via
* Modifying README.md after merging MIST master code
> [MIST-996] Modify README.md after merging MIST master code

- mist-client/src/main/java/edu/snu/mist/client/MISTDefaultExecutionEnvironmentImpl.java
This PR addresses #998 by 
* caching `taskNettyTransceiver` and `proxyToTask` in `Map`
Closes #998
> [MIST-998] Cache taskNettyTransceiver in client

- mist-common/src/main/java/edu/snu/mist/common/operators/StateTransitionOperator.java
This resolves #1004.
Closes #1004
> [MIST-1004] Fix indentation in StateTransitionalOperator

- mist-core/src/main/java/edu/snu/mist/core/driver/MistDriver.java
This PR resolves #MIST-1028 via
* Allocating MIST task evaluator request after MIST master evaluator allocation is done in MistDriver
> [MIST-1028] Allocate MIST tasks after MIST master allocation is finished

- mist-core/src/main/java/edu/snu/mist/core/task/QueryManager.java
- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/CheckpointManager.java
- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/DefaultCheckpointManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/ApplicationInfo.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultApplicationInfoImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/Group.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAllocationTableModifierImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAwareQueryManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupMap.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/DefaultGroupMergerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/DefaultGroupSplitterImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/DefaultAppInfoCheckpointStore.java
- mist-core/src/test/java/edu/snu/mist/core/task/checkpointing/GroupRecoveryTest.java
This PR resolves #1030.
Only the minimum amount of code was changed to directly address #1030.
The complete separation of groups and applications in checkpointing is the next step.
Closes #1030
> [MIST-1030] Separate fields from ApplicationInfo level to Group level

- mist-common/src/main/avro/checkpoint_manager.avpr
- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/CheckpointManager.java
- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/DefaultCheckpointManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/ApplicationInfo.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultApplicationInfoImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/Group.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/DefaultGroupCheckpointStore.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/GroupCheckpointStore.java
- mist-core/src/test/java/edu/snu/mist/core/task/checkpointing/GroupRecoveryTest.java
This PR addresses #1027 by
- changing the granularity of recovery from app level to group level
Closes #1027.
> [MIST-1027] Support fine-grained recovery in CheckpointManager

- mist-core/src/main/java/edu/snu/mist/core/driver/MistTaskConfigs.java
- mist-core/src/main/java/edu/snu/mist/core/shared/parameters/MqttSinkClientNumPerBroker.java
- mist-core/src/main/java/edu/snu/mist/core/shared/parameters/MqttSourceClientNumPerBroker.java
This PR resolves #1042 via
* Make command line parameters for MQTT-related variables.
> [MIST-1042] Parameterize MQTT-related variables

- mist-core/src/main/java/edu/snu/mist/core/driver/MistDriver.java
- mist-core/src/main/java/edu/snu/mist/core/driver/MistTaskConfigs.java
- mist-core/src/main/java/edu/snu/mist/core/parameters/TaskHostAddress.java
- mist-core/src/main/java/edu/snu/mist/core/shared/MQTTSharedResource.java
- mist-core/src/main/java/edu/snu/mist/core/shared/parameters/MqttSinkClientNumPerBroker.java
- mist-core/src/main/java/edu/snu/mist/core/shared/parameters/MqttSourceClientNumPerBroker.java
This PR resolves #1041 via
* Add `taskHostname` in mqtt client ID
> [MIST-1041] Fix Mqtt connection exception in Yarn cluster

- mist-core/src/main/java/edu/snu/mist/core/master/allocation/ApplicationAwareQueryAllocationManager.java
This PR resolves #1049 via
* Adding a new task list element when a new group comes in
> [MIST-1049] Fix non-group-aware query allocation on AAQAM

- mist-core/src/main/java/edu/snu/mist/core/driver/MistDriver.java
This PR resolves #1065 via
* Solve the timing issue in setting up master-to-task connection in `MistDriver`
> [MIST-1065] Fix possible timing issue in MistDriver

- mist-core/src/main/java/edu/snu/mist/core/task/merging/ImmediateQueryMergingStarter.java
> [MIST-1070] Reuse class loader in query starter

- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/DefaultCheckpointManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/ApplicationInfo.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultApplicationInfoImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/Group.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAwareQueryManagerImpl.java
The PR addresses #1068.
Closes #1068.
> [MIST-1068] Move queryStarter and queryRemover from Group to ApplicationInfo

- mist-core/src/main/java/edu/snu/mist/core/master/DefaultApplicationCodeManager.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/AsyncDiskQueryInfoStore.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/DefaultGroupCheckpointStore.java
This PR resolves #1076 
* by removing file deletion in mist task
> [MIST-1076] Fix bug in Jar file creation

- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAwareQueryManagerImpl.java
>  [MIST-1080] Possible concurrency issue while creating apps

- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/UtilizationLoadUpdater.java
> [MIST-1083] Fix infinite load

- mist-client/src/main/java/edu/snu/mist/client/MISTQueryImpl.java
- mist-common/src/main/avro/client_to_task_msg.avpr
This PR addresses #1089 via
* Give unique vertex id for each vertex in AvroDag
> [MIST-1089] Give unique vertex id for each vertex in AvroDag

- mist-common/src/main/avro/checkpoint_manager.avpr
- mist-core/src/main/java/edu/snu/mist/core/task/ConfigDagGenerator.java
- mist-core/src/main/java/edu/snu/mist/core/task/DefaultConfigDagGeneratorImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/QueryManager.java
- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/CheckpointManager.java
- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/DefaultCheckpointManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupAwareQueryManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/DefaultGroupCheckpointStore.java
- mist-core/src/main/java/edu/snu/mist/core/task/stores/GroupCheckpointStore.java
This PR resolves #1034 via
* Decoupling query store and state checkpointing
* Implementing necessary protocols and methods
> [MIST-1034] Decouple query store and state checkpointing

- mist-core/src/main/java/edu/snu/mist/core/task/checkpointing/DefaultCheckpointManagerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/GroupMap.java
This PR resolves #1088 via
* Implement periodic checkpointing on `DefaultCheckpointManagerImpl`
> [MIST-1088] Implement periodic checkpointing

- mist-core/src/main/java/edu/snu/mist/core/shared/MQTTSharedResource.java
- mist-core/src/main/java/edu/snu/mist/core/sources/MQTTDataGenerator.java
- mist-core/src/main/java/edu/snu/mist/core/sources/MQTTSubscribeClient.java
This PR resolves #1093 by 
* trying reconnection to MQTT broker when MQTT client is closed
> [MIST-1093] Fix closed MQTT connection

- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/DefaultGroupRebalancerImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/DefaultGroupSplitterImpl.java
- mist-core/src/test/java/edu/snu/mist/core/task/groupaware/GroupSplitterTest.java
This PR resolves #1095 by 
* fixing the group split check code 
* fixing elapsedTime
>  [MIST-1095] Fix bug in GroupSplitter and GroupImpl

- mist-core/src/main/java/edu/snu/mist/core/driver/MistMasterConfigs.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/ApplicationAwareQueryAllocationManager.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/parameters/OverloadedTaskThreshold.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/parameters/UnderloadedTaskThreshold.java
- mist-core/src/main/java/edu/snu/mist/core/master/allocation/parameters/package-info.java
- mist-core/src/main/java/edu/snu/mist/core/parameters/UnderloadedTaskThreshold.java
- mist-core/src/test/java/edu/snu/mist/core/master/QueryAllocationManagerTest.java
This PR resolves #1012 via
* Randomize query allocation on AAQAM for better distribution
> [MIST-1012] Dealing with thundering herd

- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/DefaultGroupImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/Group.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/DefaultGroupSplitterImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/GroupSplitter.java
This PR resolves #1096.
Closes #1096
> [MIST-1096] Split groups do not have the same ExecutionDags

- mist-core/src/main/java/edu/snu/mist/core/task/DefaultPhysicalOperatorImpl.java
- mist-core/src/main/java/edu/snu/mist/core/task/NonBlockingQueueSourceOutputEmitter.java
- mist-core/src/main/java/edu/snu/mist/core/task/PhysicalOperator.java
This PR addresses #1015.
Closes #1015.
> [MIST-1015] Remove LatestDataTimestamp and LatestWatermarkTimestamp from PhysicalOperator

- mist-core/src/main/java/edu/snu/mist/core/configs/MistCommandLineOptions.java
- mist-core/src/main/java/edu/snu/mist/core/configs/MistMasterConfigs.java
- mist-core/src/main/java/edu/snu/mist/core/master/ProxyToTaskMap.java
- mist-core/src/main/java/edu/snu/mist/core/master/recovery/DistributedRecoveryScheduler.java
- mist-core/src/main/java/edu/snu/mist/core/master/recovery/parameters/RecoveryUnitSize.java
- mist-core/src/main/java/edu/snu/mist/core/master/recovery/parameters/package-info.java
This PR addresses #986 via
* Implement distributed recovery policy
Closes #986
> [MIST-986] Implement distributed recovery policy

- mist-core/src/main/java/edu/snu/mist/core/shared/MQTTNoSharedResource.java
- mist-core/src/main/java/edu/snu/mist/core/shared/MQTTResource.java
- mist-core/src/main/java/edu/snu/mist/core/shared/MQTTSharedResource.java
- mist-core/src/main/java/edu/snu/mist/core/sinks/MqttSink.java
> [MIST-1122] Reconnect MQTT sink client

- mist-core/src/main/java/edu/snu/mist/core/task/DefaultQueryImpl.java
> [MIST-1124] Use AtomicReference in setting group

- mist-core/src/main/java/edu/snu/mist/core/task/groupaware/rebalancer/DefaultGroupRebalancerImpl.java
This PR resolves #1152 by 
* fixing comparator in GroupRebalancer
> [MIST-1152] Fix IllegalArgumentException in GroupRebalancer

- mist-core/src/main/java/edu/snu/mist/core/Mist.java
- mist-core/src/main/java/edu/snu/mist/core/MistLauncher.java
- mist-core/src/main/java/edu/snu/mist/core/parameters/DriverMemorySize.java
This PR resolves #1146 by 
* adding `DriverMemorySize` to command line parameters.
> [MIST-1146] Configure driver memory size

- mist-core/src/main/java/edu/snu/mist/core/operators/ApplyStatefulOperator.java
- mist-core/src/main/java/edu/snu/mist/core/operators/ReduceByKeyOperator.java
- mist-core/src/main/java/edu/snu/mist/core/operators/window/FixedSizeWindowOperator.java
- mist-core/src/main/java/edu/snu/mist/core/operators/window/SessionWindowOperator.java
- mist-core/src/test/java/edu/snu/mist/core/task/checkpointing/GroupRecoveryTest.java
This PR closes #1150 via
* Using `ObjenesisInstantiationStrategy()` for `Cloner`.
> [MIST-1150] Fix IllegalArgumentException on Cloner

- mist-core/src/main/java/edu/snu/mist/core/rpc/DefaultDriverToMasterMessageImpl.java
This PR closes #1172 via
* Request a new task when failure occurs in an asynchronous way.
> [MIST-1172] Request a new task when failure occurs
